a_positive_homepage:
    path:     /index
    defaults: { _controller: APositiveBundle:Default:index }

info_page:
    resource: "@APositiveBundle/Controller/DefaultController.php"
    type:     annotation
    prefix:   /index

