a_positive_homepage:
    path:     /index
    defaults: { _controller: APositiveBundle:Default:index }

a_positive_about:
    path:     /about
    defaults: { _controller: APositiveBundle:Default:about }

a_positive_backend_login:
    path:     /onestop/login
    defaults: { _controller: APositiveBundle:Default:login }
    
a_positive_backend:
    path:     /onestop/
    defaults: { _controller: APositiveBundle:Default:backend }