a_positive_homepage:
    resource: "@APositiveBundle/Controller/DefaultController.php"
    type:     annotation
    prefix:   /index

a_positive_backend_login_page:
    path:     /onestop/login
    defaults: { _controller: APositiveBundle:Backend:loginpage }

a_positive_backend_checklogin:
    path:     /onestop/checklogin
    defaults: { _controller: APositiveBundle:Backend:checklogin }
    
a_positive_backend_register:
    path:     /onestop/register
    defaults: { _controller: APositiveBundle:Backend:register }
    
a_positive_backend_dashboard:
    path:     /onestop/
    defaults: { _controller: APositiveBundle:Backend:index }