a_positive_homepage:
    resource: "@APositiveBundle/Controller/DefaultController.php"
    type:     annotation
    prefix:   /index

a_positive_backend_login:
    path:     /onestop/login
    defaults: { _controller: APositiveBundle:Default:login }
    
a_positive_backend:
    path:     /onestop/
    defaults: { _controller: APositiveBundle:Default:backend }
