parameters:
#    a_positive_test.example.class: APositive\TestBundle\Example

services:
#    a_positive_test.example:
#        class: %a_positive_test.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
